


CREATE TABLE [dbo].[MyImageTable](
	[ImageID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [text] NULL,
	[Image] [image] NULL,
 CONSTRAINT [PK_MyImageTable] PRIMARY KEY CLUSTERED 
(
	[ImageID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
